### ISSUE TITLE
todo (commands)

### ISSUE THREAD

**Issue by acrylic-style** [acrylic-style/SpicyAzisaBan#1]
- `<>` - required (必須)
- `[]` - optional (オプション)

- [x] `gban <player> [reason] [server] [--all]` - (server指定なしで全鯖)プレイヤーをBAN
- [x] `ban <player> [reason] [server] [--all]` - (server指定なしで現在いる鯖)プレイヤーをBAN
- [x] `gipban <target=player/ip> [server]` - (server指定なしで全鯖)プレイヤーをIPBAN
- [x] `ipban <target=player/ip> [server]` - (server指定なしで現在いる鯖)プレイヤーをIPBAN
- [x] `gtempban <player> [reason] [server] [time]` - (server指定なしで全鯖)プレイヤーを期限BAN
- [x] `tempban <player> [reason] [server] [time]` - (server指定なしで現在いる鯖)
- [x] `gtempipban <target=player/ip> [reason] [server] [time]` - (server指定なしで全鯖)プレイヤーを期限IPBAN
- [x] `tempipban <target=player/ip> [reason] [server] [time]` - (server指定なしで現在いる鯖)プレイヤーを期限IPBAN
- [x] `gmute <player> [reason] [server] [--all]` - (server指定なしで全鯖)プレイヤーをミュート
- [x] `mute <player> [reason] [server] [--all]` - (server指定なしで現在いる鯖)プレイヤーをミュート
- [x] `gtempmute <player> [reason] [server] [time]` - (server指定なしで全鯖)プレイヤーを期限ミュート
- [x] `tempmute <player> [reason] [server] [time]` - (server指定なしで現在いる鯖)プレイヤーを期限ミュート
- [x] `gipmute <target=player/ip> [reason] [server]` - (server指定なしで全鯖)プレイヤーをIPミュート
- [x] `ipmute <target=player/ip> [reason] [server]` - (server指定なしで現在いる鯖)プレイヤーをIPミュート
- [x] `gtempipmute <target=player/ip> [reason] [server] [time]` - (server指定なしで全鯖)プレイヤーを期限IPミュート
- [x] `tempipmute <target=player/ip> [reason] [server] [time]` - (server指定なしで現在いる鯖)プレイヤーを期限IPミュート
- [x] `gwarning <player> [reason] [server]` - (server指定なしで全鯖)プレイヤーを警告
- [x] `warning <player> [reason] [server]` - (server指定なしで現在いる鯖)プレイヤーを警告
- [x] `gcaution <player> [reason] [server]` - (server指定なしで全鯖)プレイヤーを注意
- [x] `caution <player> [reason] [server]` - (server指定なしで現在いる鯖)プレイヤーを注意
- [x] `gkick <player> [reason] [server]` - server指定なしでProxyからkick、指定ありで被処罰者が指定した鯖にいる場合はロビーに強制送還
- [x] `kick <player> [reason] [server]` - server指定なしで被処罰者が現在いる鯖にいる場合はロビーに強制送還
- [x] `gnote <player> [reason] [server]` - (server指定なしで全鯖)プレイヤーをnote
- [x] `note <player> [reason] [server]` - (server指定なしで現在いる鯖)プレイヤーをnote
- [x] `unban <target=player> <reason> [server]` - プレイヤーのBANを解除
- [x] `unmute <target=player> <reason> [server]` - プレイヤーのミュートを解除
- [x] `unpunish <id=...> <reason>` - 処罰を解除
- [x] `changereason <id> <reason>` - 処罰理由を変更
- [x] `seen <player/ip>` - Essentialsの/seenみたいなやつ
- [x] `history <target=player/ip> [page=...] [--active] [--all] [--ip/-i] [--only/-o]` - AdvancedBanの/historyみたいなやつ
- [x] `check <player/ip>` - AdvancedBanの/checkみたいなやつ
- [x] `banlist [type=...] [server=...] [page=...] [--active] [--all]` - AdvancedBanの/banlistみたいなやつだけどいろいろ指定できるようにした
- [x] `warns` - (誰でも使える)AdvancedBanの/warnsみたいなやつ
- [x] `addproof <punish id> <text>` - 処罰に証拠を添付
- [x] `delproof <proof id>` - 証拠を削除
- [x] `proofs <punish id>` - 処罰に添付された証拠を表示

cautionとは: warnに似たようなものだがwarn3回で自動BANのシステムが存在しない(カウントされない)
口頭注意のコマンド版みたいな感じで使用可能
