### ISSUE TITLE
todo (general)

### ISSUE THREAD

**Issue by acrylic-style** [acrylic-style/SpicyAzisaBan#3]
- [x] 1:30 AM: https://discord.com/channels/695918397002874880/874216630949937152/875415862658617394
- [x] Implement IPAddressContext
- [x] create table `unpunish`, `proofs`, `usercache`
  - unpunish: id (primary key, bigint), punish_id (bigint), reason (varchar), timestamp (bigint), operator (varchar)
  - proofs: id (primary key, bigint), punish_id (bigint), text (varchar)
  - usercache: uuid (primary key, varchar), name (varchar)
- [x] stop using mojang api as they do not support geyser (bedrock) players
- [x] prevent double-punishing a player (e.g. banning an ip twice, muting a player twice)
- [x] send title every `<time>` and stays for `<time2>` if they have unread warning(s)
